# Modified by: ikeepcalm
# Forked from FireCreeper82/LOTM
# A Fan made Lord of the Mysteries plugin
# Fan made plugin for the Lord of the Mysteries novel by Cuttlefish That Loves Diving
# Not affiliated with the author or the novel in any way, though it was an inspiration
# Adapted to be distributed as a standalone plugin on ukrainian minecraft server

# Beyonder creatures and spirits
enable-mobs: true

# Explosions rollback
enable-explosions: true

enable-spirits: true

enable-boss-realm: false

anchor-location: null

transformed-blocks: []

# Sleep / Insomnia notification settings
notification: ACTIONBAR # Possible values: ACTIONBAR, CHAT
sleep-message: "&9☽ &7|&f Гравець &6 {player} &fбажає пропустити цю ніч"
insomnia-message: "&e☀ &7|&f Гравець &6 {player} &cне бажає &fпропускати цю ніч!"

# Emporium prices
recipe: 10
potion: 40
characteristic: 20
ingredient: 5