# Modified by: ikeepcalm
# Forked from FireCreeper82/LOTM
# A Fan made Lord of the Mysteries plugin
# Fan made plugin for the Lord of the Mysteries novel by Cuttlefish That Loves Diving
# Not affiliated with the author or the novel in any way, though it was an inspiration
# Adapted to be distributed as a standalone plugin on ukrainian minecraft server

enable-mobs: true