name: LordOfTheMinecraft
version: '${project.version}'
main: dev.ua.ikeepcalm.LordOfTheMinecraft
api-version: '1.20'
authors: [ FireCreeper82, ikeepcalm ]
description: A Fan made Lord of the Mysteries plugin
depend: [ Citizens, ProtocolLib ]
commands:
  beyonder:
    description: Make yourself a Beyonder
    usage: /<cmd>
  items:
    description: Give yourself the items from your pathway
    usage: /<cmd>
  disable-threads:
    description: Choose the Spirit Body Threads you want to see
    usage: /<cmd>
  exclude-entities:
    description: Choose the Spirit Body Threads of the entities you don't want to see
    usage: /<cmd>
  thread-length:
    description: Choose the max distance for the Spirit Body Threads you want to see
    usage: /<cmd>
  configure-threads:
    description: Configure the Spirit Body Threads you want to see
    usage: /<cmd>
  test:
    description: Used for testing various things
    usage: /<cmd>
  spawn:
    description: Spawn a custom entity
    usage: /<cmd>
  ability-info:
    description: Get the infos about your abilities
    usage: /<cmd>
  spirit:
    description: Spawn a spirit
    usage: /<cm>
  artifact:
    description: Get a random Sealed Artifact (Testing only)
    usage: /<cmd>