name: LordOfTheMinecraft
version: '${project.version}'
main: dev.ua.ikeepcalm.LordOfTheMinecraft
api-version: '1.21'
authors: [ FireCreeper82, ikeepcalm ]
description: A Fan made Lord of the Mysteries plugin
depend: [ CoreProtect, Citizens, NBTAPI ]
commands:
  boon:
    description: Make yourself a Beyonder
    usage: /<cmd>
  test:
    description: Used for testing various things
    usage: /<cmd>
  spawn:
    description: Spawn a custom entity
    usage: /<cmd>
  spirit:
    description: Spawn a spirit
    usage: /<cmd>
  mi9:
    description: Only for the MI9 members!
    usage: /<cmd>
  sleep:
    description: Ask the server to skip the night
    usage: /<cmd>
  insomnia:
    description: Ask the server to not skip the night
    usage: /<cmd>
  emporium:
    description: Open the emporium
    usage: /<cmd>
permissions:
  lordoftheminecraft.boon:
    description: Allows the player to become a Beyonder
    default: true
  lordoftheminecraft.test:
    description: Allows the player to test various things
    default: true
  lordoftheminecraft.spawn:
    description: Allows the player to spawn a custom entity
    default: true
  lordoftheminecraft.spirit:
    description: Allows the player to spawn a spirit
    default: true
  lordoftheminecraft.mi9:
    description: Allows the player to use the MI9 command
    default: true